server:
  port: 10330

spring:
  application:
    name: byeol23-front
  profiles:
    active: dev



eureka:
  client:
    healthcheck:
      enabled: true
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://127.0.0.1:10338/dashboard/eureka
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.hostname}:${spring.application.instance_id:${server.port}}

logging:
  level:
    root: info
