spring:
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      password: ${REDIS_PASSWORD}
      database: ${REDIS_DATABASE}

minio:
  host: storage.java21.net
  port: 8000
  access-key: V2CnisSrBMa0w2QtE8cP
  secret-key: Bfyx9qcRRI2J7LHF5r5ZoFFWIFSZ40d4K9FEpDnh
  bucket-name: byeol23